'use strict';
function renderColList(){var container=document.getElementById('colList');container.replaceChildren();columns.forEach(function(col,idx){var item=document.createElement('div');item.className='col-item p-3';item.dataset.index=idx;var wrap=document.createElement('div');wrap.className='flex items-center justify-between';var left=document.createElement('div');left.className='flex items-center gap-2 flex-1';var drag=document.createElement('span');drag.className='drag-handle text-xl cursor-move';drag.textContent='☰';var label=document.createElement('span');label.className='font-bold text-sm';label.textContent=(idx+1)+'. '+col;left.append(drag,label);var actions=document.createElement('div');actions.className='flex gap-1';[['⬆️',function(){moveColumnUp(idx);}],['⬇️',function(){moveColumnDown(idx);}],['删',function(){deleteColumn(col);}]].forEach(function(spec,i){var b=document.createElement('button');b.className=(i<2?'bg-blue-500':'bg-red-500')+' text-white px-2 py-1 rounded text-xs';b.textContent=spec[0];b.onclick=spec[1];actions.appendChild(b);});wrap.append(left,actions);item.appendChild(wrap);container.appendChild(item);});setupDragAndDrop();}
function setupDragAndDrop(){var items=document.querySelectorAll('.col-item'),isTouch='ontouchend' in document,dragged=null;items.forEach(function(item){if(isTouch){item.draggable=false;return;}item.draggable=true;item.addEventListener('dragstart',function(e){dragged=item;item.style.opacity='.5';e.dataTransfer.effectAllowed='move';});item.addEventListener('dragend',function(){item.style.opacity='';dragged=null;});item.addEventListener('dragover',function(e){e.preventDefault();});item.addEventListener('drop',function(e){e.preventDefault();if(!dragged||dragged===item)return;var from=Number(dragged.dataset.index),to=Number(item.dataset.index);if(Number.isInteger(from)&&Number.isInteger(to)){var temp=columns[from];columns[from]=columns[to];columns[to]=temp;renderColList();renderPage();scheduleAutoSave();showToast('列顺序已更新');}});});}
function moveColumnUp(i){if(i>0){var t=columns[i];columns[i]=columns[i-1];columns[i-1]=t;renderColList();renderPage();scheduleAutoSave();showToast('列顺序已更新');}}
function moveColumnDown(i){if(i<columns.length-1){var t=columns[i];columns[i]=columns[i+1];columns[i+1]=t;renderColList();renderPage();scheduleAutoSave();showToast('列顺序已更新');}}
function openColModal(){renderColList();document.getElementById('colModal').style.display='flex';}
function closeColModal(){document.getElementById('colModal').style.display='none';renderPage();}
function addColumn(){var input=document.getElementById('newColName'),newCol=input.value.trim();if(newCol&&!columns.includes(newCol)){columns.push(newCol);db.forEach(function(r){r[newCol]='';});renderColList();renderPage();rebuildSearchIndex();scheduleAutoSave();showToast('已添加列: '+newCol);input.value='';}else if(columns.includes(newCol))showToast('列名已存在',true);}
function deleteColumn(col){if(col==='实际数量'||col==='实际价格'){showToast('⚠️ 核心列不能删除',true);return;}if(confirm('确定删除列 "'+col+'" 吗？数据将丢失！')){var i=columns.indexOf(col);if(i!==-1){columns.splice(i,1);db.forEach(function(r){delete r[col];});renderColList();renderPage();rebuildSearchIndex();scheduleAutoSave();showToast('已删除列: '+col);}}}
async function hardReset(){if(confirm('⚠️ 确定清空所有数据吗？此操作不可恢复！')){db=[];columns=['实际数量','实际价格','商品名称','编码','价格'];normalizeSpecialColumns();currentPage=0;undoStack=[];rebuildSearchIndex();renderPage();await clearPersistedSession();showToast('已清空所有数据');}}
