'use strict';
var STORAGE_DB='sanfei_inventory_v4';
var STORAGE_STORE='sessions';
var STORAGE_KEY='current';
var saveTimer=null;
var inventorySessionId=null;
var storageQueue=Promise.resolve();
function newInventorySessionId(){return 'history:'+Date.now()+':'+Math.random().toString(36).slice(2);}
function openInventoryDb(){return new Promise(function(resolve,reject){if(!('indexedDB' in window)){reject(new Error('此浏览器无法自动保存'));return;}var finished=false;var timer=setTimeout(function(){finished=true;reject(new Error('自动保存连接超时，请关闭同网站其他标签页后重试'));},15000);var req=indexedDB.open(STORAGE_DB,1);req.onupgradeneeded=function(){var idb=req.result;if(!idb.objectStoreNames.contains(STORAGE_STORE))idb.createObjectStore(STORAGE_STORE);};req.onsuccess=function(){clearTimeout(timer);if(finished){req.result.close();return;}finished=true;resolve(req.result);};req.onerror=function(){clearTimeout(timer);finished=true;reject(req.error);};req.onblocked=function(){clearTimeout(timer);finished=true;reject(new Error('自动保存被其他页面占用，请关闭同网站其他标签页后重试'));};});}
function sessionSnapshot(){if(!inventorySessionId)inventorySessionId=newInventorySessionId();return JSON.parse(JSON.stringify({id:inventorySessionId,version:VERSION,db:db,columns:columns,currentPage:currentPage,filter:currentInventoryFilter,unknownBarcodes:unknownBarcodes,currentImportFileName:currentImportFileName,sourceQtyColumn:sourceQtyColumn,savedAt:Date.now()}));}
function queueStorage(work){var task=storageQueue.then(work);storageQueue=task.catch(function(){});return task;}
async function serverRequest(url,method,data){var response=await fetch(url,{method:method||'GET',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});var result=await response.json();if(!response.ok)throw new Error(result.error||'本地文件保存失败');return result;}

function usesLocalServer(){return /^https?:$/.test(location.protocol)&&/^(localhost|127\.0\.0\.1)$/.test(location.hostname)&&location.port==='18749';}
function browserRequest(url,method,data){return openInventoryDb().then(function(idb){return new Promise(function(resolve,reject){var tx=idb.transaction(STORAGE_STORE,method==='GET'?'readonly':'readwrite'),st=tx.objectStore(STORAGE_STORE),result={ok:true};var timedOut=false,timer=setTimeout(function(){timedOut=true;try{tx.abort();}catch(e){}},20000);tx.oncomplete=function(){clearTimeout(timer);idb.close();resolve(result);};tx.onerror=tx.onabort=function(){clearTimeout(timer);idb.close();reject(new Error(timedOut?'自动保存超时，请重试':(tx.error&&tx.error.message)||'浏览器保存失败'));};if(method==='GET'){var records=[],current=null;var req=st.openCursor();req.onsuccess=function(){var c=req.result;if(c){if(c.key===STORAGE_KEY)current=c.value;else if(String(c.key).indexOf('history:')===0)records.push(c.value);c.continue();}else result={records:records,current:current};};}else if(method==='DELETE')st.delete(STORAGE_KEY);else{st.put(data,STORAGE_KEY);if(data.db.length){st.put(data,data.id);var keys=[];var q=st.openCursor();q.onsuccess=function(){var c=q.result;if(c){if(String(c.key).indexOf('history:')===0)keys.push(String(c.key));c.continue();}else{keys.sort(function(a,b){return Number(a.split(':')[1])-Number(b.split(':')[1])||a.localeCompare(b);});while(keys.length>50){var i=keys.findIndex(function(k){return k!==data.id;});st.delete(keys.splice(i,1)[0]);}}};}}});});}
function localRequest(url,method,data){return usesLocalServer()?serverRequest(url,method,data):browserRequest(url,method||'GET',data);}

function writeSession(data){return queueStorage(function(){return localRequest('/api/session','POST',data);});}
async function persistSession(){try{await writeSession(sessionSnapshot());return true;}catch(e){console.warn('自动保存失败',e);showToast(db.length?'❌ 盘点保存失败：'+e.message+'；请文件备份，勿关闭页面':'❌ 自动保存不可用：'+e.message,true);return false;}}
function scheduleAutoSave(){if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(function(){saveTimer=null;persistSession();},500);}
async function saveBeforeInventorySwitch(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}return persistSession();}
function applySavedSession(data){inventorySessionId=data.id||newInventorySessionId();db=data.db;columns=Array.isArray(data.columns)?data.columns:[];currentPage=Number.isFinite(data.currentPage)?data.currentPage:0;currentInventoryFilter=data.filter||'all';unknownBarcodes=data.unknownBarcodes||{};currentImportFileName=data.currentImportFileName||'';sourceQtyColumn=data.sourceQtyColumn||detectSourceQtyColumn(columns,db);undoStack=[];normalizeSpecialColumns();rebuildSearchIndex();renderPage();}
async function readInventorySessions(){await storageQueue;var result=await localRequest('/api/history');var entries=result.records.map(function(data){return {key:data.id,data:data};});if(result.current)entries.push({key:STORAGE_KEY,data:result.current});return entries;}
async function restoreSession(){try{var entries=await readInventorySessions(),entry=entries.find(function(e){return e.key===STORAGE_KEY;});if(entry&&Array.isArray(entry.data.db)&&entry.data.db.length){applySavedSession(entry.data);showToast('✅ 已恢复上次盘点 '+db.length+' 条');return true;}}catch(e){console.warn('恢复失败',e);showToast('❌ 历史读取失败；请勿清除网站数据，可导入文件备份恢复',true);}return false;}
async function clearPersistedSession(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;}await queueStorage(function(){return localRequest('/api/current','DELETE');});inventorySessionId=null;}
async function importLegacyHistory(file){if(isProcessing)return;isProcessing=true;try{var items=JSON.parse(await file.text());if(!Array.isArray(items))throw new Error('迁移文件格式错误');if(!await saveBeforeInventorySwitch())return;var current=sessionSnapshot();items.sort(function(a,b){return a.savedAt-b.savedAt;});for(var item of items){if(!item.id)item.id=newInventorySessionId();await writeSession(item);}await writeSession(current);showToast('✅ 旧历史已保存到本地文件夹，最多保留50份');}catch(e){showToast('❌ 迁移未完成：'+e.message,true);}finally{isProcessing=false;}}
async function openInventoryHistory(){
  if(isProcessing){showToast('⏳ 正在处理中...');return;}
  isProcessing=true;
  try{
    if(!await saveBeforeInventorySwitch())return;
    var entries=await readInventorySessions(),records=entries.filter(function(e){return String(e.key).indexOf('history:')===0&&e.data&&Array.isArray(e.data.db)&&e.data.db.length;}).sort(function(a,b){return b.data.savedAt-a.data.savedAt;});
    var previous=document.getElementById('inventoryHistory');if(previous)previous.remove();
    var overlay=document.createElement('div');overlay.id='inventoryHistory';overlay.style.cssText='position:fixed;inset:0;z-index:1000;background:rgba(0,0,0,.55);display:flex;align-items:center;justify-content:center;padding:16px';
    var panel=document.createElement('div');panel.style.cssText='background:white;color:#111827;border-radius:16px;padding:20px;width:560px;max-width:100%;max-height:80vh;overflow:auto';
    var title=document.createElement('h2');title.textContent='历史盘点记录';title.style.cssText='font-size:20px;font-weight:bold;margin-bottom:12px';panel.appendChild(title);
    var note=document.createElement('p');note.textContent=usesLocalServer()?'记录保存到电脑系统目录，最多50份。':'此处是浏览器自动保存的最近50份记录。清除网站数据会删除这些记录；请另备份到“文件 → 盘点历史电子单”。';panel.appendChild(note);
    var migration=document.createElement('input');migration.type='file';migration.accept='.json';migration.title='导入旧浏览器历史迁移文件';migration.onchange=function(){if(this.files[0])importLegacyHistory(this.files[0]);};panel.appendChild(migration);
    var close=document.createElement('button');close.textContent='关闭';close.style.cssText='padding:10px 18px;margin:12px 0;background:#e5e7eb;border-radius:8px';close.onclick=function(){overlay.remove();};panel.appendChild(close);
    if(!records.length){var empty=document.createElement('p');empty.textContent='暂无历史盘点记录';panel.appendChild(empty);}
    records.forEach(function(entry){var row=document.createElement('div');row.style.cssText='border-top:1px solid #ddd;padding:14px 0';var label=document.createElement('p');label.textContent=(entry.data.currentImportFileName||'未命名盘点')+' · '+entry.data.db.length+' 项 · '+new Date(entry.data.savedAt).toLocaleString();row.appendChild(label);var button=document.createElement('button');button.textContent=entry.key===inventorySessionId?'当前盘点':'恢复此盘点';button.disabled=entry.key===inventorySessionId;button.style.cssText='padding:10px 16px;margin-top:8px;background:#2563eb;color:white;border-radius:8px';button.onclick=async function(){if(isProcessing)return;if(!confirm('恢复此盘点？当前盘点会先保存到历史，不会丢失。'))return;isProcessing=true;try{if(!await saveBeforeInventorySwitch())return;await writeSession(entry.data);applySavedSession(JSON.parse(JSON.stringify(entry.data)));overlay.remove();showToast('✅ 已恢复历史盘点，可继续盘点或导出');}catch(e){showToast('❌ 恢复失败，当前盘点保留',true);console.warn(e);}finally{isProcessing=false;}};row.appendChild(button);panel.appendChild(row);});
    overlay.appendChild(panel);document.body.appendChild(overlay);
  }catch(e){console.warn(e);showToast('❌ 读取历史失败，当前盘点保留',true);}finally{isProcessing=false;}
}
