'use strict';
const http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path');
const ROOT=__dirname,DIR=path.join(ROOT,'飞速盘点历史记录'),PORT=18749;
const valid=d=>d&&/^history:[0-9]+:[a-z0-9]+$/.test(d.id)&&Array.isArray(d.db)&&Array.isArray(d.columns)&&Number.isFinite(d.savedAt);
const file=id=>path.join(DIR,id.replaceAll(':','_')+'.json');
async function atomic(p,data){const t=p+'.tmp';try{await fs.writeFile(t,JSON.stringify(data),'utf8');const h=await fs.open(t,'r+');try{await h.sync();}finally{await h.close();}await fs.rename(t,p);}finally{await fs.rm(t,{force:true});}}
async function records(){const out=[];for(const n of await fs.readdir(DIR)){if(!/^history_[0-9]+_[a-z0-9]+\.json$/.test(n))continue;const d=JSON.parse(await fs.readFile(path.join(DIR,n),'utf8'));if(!valid(d))throw Error('历史文件损坏：'+n);out.push(d);}return out;}
async function trim(current){const all=await records();all.sort((a,b)=>Number(a.id.split(':')[1])-Number(b.id.split(':')[1])||a.id.localeCompare(b.id));while(all.length>50){const i=all.findIndex(d=>d.id!==current);if(i<0)throw Error('清理失败');await fs.unlink(file(all.splice(i,1)[0].id));}}
let queue=Promise.resolve();
async function api(req,res,url){const mutate=async()=>{if(req.method==='GET'&&url.pathname==='/api/history'){const all=await records();let current=null;try{current=JSON.parse(await fs.readFile(path.join(DIR,'current.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}return {records:all,current};}
if(req.method==='DELETE'&&url.pathname==='/api/current'){await fs.rm(path.join(DIR,'current.json'),{force:true});return {ok:true};}
if(req.method==='POST'&&url.pathname==='/api/session'){let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>64*1024*1024)throw Error('单份记录超过64MB');chunks.push(chunk);}const d=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!valid(d))throw Error('盘点文件格式无效');if(d.db.length)await atomic(file(d.id),d);await atomic(path.join(DIR,'current.json'),d);await trim(d.id);return {ok:true};}throw Error('不支持的请求');};
const task=queue.then(mutate);queue=task.catch(()=>{});try{const result=await task;res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(result));}catch(e){res.writeHead(500,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify({error:e.message}));}}
async function main(){await fs.mkdir(DIR,{recursive:true});const server=http.createServer(async(req,res)=>{try{if(req.headers.host!==`127.0.0.1:${PORT}`&&req.headers.host!==`localhost:${PORT}`){res.writeHead(403);return res.end();}const origin=req.headers.origin;if(origin&&origin!==`http://127.0.0.1:${PORT}`&&origin!==`http://localhost:${PORT}`){res.writeHead(403);return res.end();}const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return api(req,res,url);const name=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname);if(!/^\/(index\.html|migration\.html|js\/[\w-]+\.js|css\/[\w-]+\.css|assets\/audio\/[\w-]+\.wav)$/.test(name)){res.writeHead(404);return res.end();}const body=await fs.readFile(path.join(ROOT,name));const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.wav':'audio/wav'};res.writeHead(200,{'Content-Type':types[path.extname(name)],'Cache-Control':'no-store'});res.end(body);}catch(e){res.writeHead(404);res.end();}});server.on('error',e=>{console.error(e.message);process.exitCode=1;});server.listen(PORT,'127.0.0.1',()=>{console.log('FEISU: http://127.0.0.1:'+PORT);console.log('历史目录: '+DIR);});}
if(require.main===module)main();module.exports={valid,atomic,records,trim,main};
